version: '3.7'

services:
  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
        - ./data:/var/lib/postgresql/data